### ISSUE TITLE
Fehler: No tidy method for objects of class stsNC

### ISSUE THREAD

**Issue by xong** [InitiativeGrundrechte/Nowcasting_COVID-19#1]
Hallo,

ich würde das Skript gern unter Windows 10 ausführen. Nach einigen Startschwierigkeiten konnte ich alle Abhängigkeiten installieren.

Allerdings bekomme ich nun bei der Ausführung mittels `python nowcasting` folgende Fehlermeldung:
> Error: No tidy method for objects of class stsNC
> In addition: Warning message:
> In nowcast(now = now, when = nowcastDates, data = as.data.frame(country_weibull),  :
>   25 cases with a delay longer than D=21 days forced to have a delay of D days.
> 
> Traceback (most recent call last):
>   File "nowcasting", line 24, in <module>
>     robjects.r('source(\'./nowcasting_covid19_saxony.R\')');
>   File "C:\Program Files\Python38\Lib\site-packages\rpy2\robjects\__init__.py", line 416, in __call__
>     res = self.eval(p)
>   File "C:\Program Files\Python38\Lib\site-packages\rpy2\robjects\functions.py", line 197, in __call__
>     return (super(SignatureTranslatedFunction, self)
>   File "C:\Program Files\Python38\Lib\site-packages\rpy2\robjects\functions.py", line 125, in __call__
>     res = super(Function, self).__call__(*new_args, **new_kwargs)
>   File "C:\Program Files\Python38\Lib\site-packages\rpy2\rinterface_lib\conversion.py", line 44, in _
>     cdata = function(*args, **kwargs)
>   File "C:\Program Files\Python38\Lib\site-packages\rpy2\rinterface.py", line 621, in __call__
>     raise embedded.RRuntimeError(_rinterface._geterrmessage())
> rpy2.rinterface_lib.embedded.RRuntimeError: Error: No tidy method for objects of class stsNC

Laut https://community.rstudio.com/t/tidying-an-object-of-class-mediate/60665 soll es helfen, die _development version_ von [broom](https://github.com/tidymodels/broom) zu installieren, allerdings bleibt der Fehler bestehen.

Habt ihr vielleicht einen Tipp, was ich noch versuchen könnte?

Ich verwende Python 3.8.2 sowie R 4.0.0.

Danke und liebe Grüße
Robert

Nachtrag: Auch der direkte Aufruf mittels `rscript` liefert (natürlich) den selben Fehler.

**Comment by InitiativeGrundrechte** [comment]
Bei mir läuft es mit R Version 3.6.1 und Python 3.7.5 (Ubuntu eoan). Zu Windows kann ich leider nichts sagen.

**Comment by InitiativeGrundrechte** [comment]
Hier läuft es mit R Version 3.6.1 und Python 3.7.5 (Ubuntu eoan). Zu Windows kann ich leider nichts sagen.
